// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonotouchExamples {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				return ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
			}
			set {
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				return ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
			}
			set {
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("exampleLabel")]
		private MonoTouch.UIKit.UILabel exampleLabel {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("exampleLabel")));
			}
			set {
				this.SetNativeField("exampleLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("infoButton")]
		private MonoTouch.UIKit.UIButton infoButton {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("infoButton")));
			}
			set {
				this.SetNativeField("infoButton", value);
			}
		}
	}
}
